services:
  aggapp:
    container_name: aggapp
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: development
      SIDEKIQ_REDIS_URL: redis://aggcache:6379/0
      DATABASE_URL: postgres://pod4lib:pod4lib@aggdb:5432/aggregator
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - aggdb
      - aggcache

  aggworker:
    container_name: aggworker
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec sidekiq
    environment:
      SIDEKIQ_REDIS_URL: redis://aggcache:6379/0
      DATABASE_URL: postgres://pod4lib:pod4lib@aggdb:5432/aggregator
      RAILS_MAX_THREADS: 5
    volumes:
      - .:/usr/src/app
    depends_on:
      - aggdb
      - aggcache

  aggdb:
    container_name: aggdb
    image: postgres:16.10
    environment:
      POSTGRES_USER: pod4lib
      POSTGRES_PASSWORD: pod4lib
      POSTGRES_DB: aggregator
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  aggcache:
    container_name: aggcache
    image: redis:8.2
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

volumes:
  db:
  cache:
